- OWNERS
- OWNERS_ALIASES
This PR adds OWNERS_ALIASES for knative-eventing similar way as for [knative-serving](https://github.com/openshift/knative-serving/blob/master/OWNERS_ALIASES).
> add OWNERS_ALIASES for knative-eventing

- openshift/e2e-tests-openshift.sh
- openshift/kubecon-demo.sh
knative build/serving/eventing are pre-installed by CI before running the demo. Eventing is installed from sources, build and serving are installed as dependencies of eventing. The scripts do not use OLM.
> Run kubecon demo as part of e2e tests

- openshift/kubecon-demo.sh
* the default scale-to-zero period is 5 mins
The nightly job currently fails, this is the attempt to fix it (https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-ci-openshift-knative-eventing-release-0.2-e2e/30)
> Wait longer for the dumpy deployment to go down

- Makefile
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/generate-dockerfiles.sh
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/fanoutsidecar/Dockerfile
- openshift/ci-operator/knative-images/in-memory-channel-controller/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/ci-operator/knative-test-images/k8sevents/Dockerfile
Use registry.svc.ci.openshift.org/openshift/origin-v3.11:base as the
base image. The FROM clause is ignored by ci-operator during the actual
build and is replaced by an image from ci-operator's config. Anyway,
it's replaced with the same image name so here we only make sure the
user knows what the base image is.
(this update comes after this change: openshift/release@7da82d8 )
> Generate Dockerfiles via script - release-0.2

- Makefile
- OWNERS
- OWNERS_ALIASES
- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/generate-dockerfiles.sh
- openshift/ci-operator/generate-release.sh
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/fanoutsidecar/Dockerfile
- openshift/ci-operator/knative-images/in-memory-channel-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/ci-operator/knative-test-images/k8sevents/Dockerfile
All of this is required for the PR in ci-operator repo to pass checks: https://github.com/openshift/release/pull/2918
When the current PR and pull/2918 are integrated I'll issue a new PR with the script that executes tests.
> Basic CI setup release-0.3 OpenShift 4

- Makefile
- openshift/e2e-tests-openshift.sh
- openshift/origin-e2e-job.yaml
This PR replaces https://github.com/openshift/knative-eventing/pull/28
Later, I'd like to setup a periodic job for the newest branch that would run the Origin's conformance tests nightly.
> Run Origin's conformance test suite via specific target

- Makefile
- openshift/e2e-tests-openshift.sh
- openshift/release/create-release-branch.sh
- openshift/release/generate-release.sh
- openshift/release/resolve.sh
Same as https://github.com/openshift/knative-eventing/pull/47 but the resulting release yaml file is not included (this is a master branch where we don't want that).
I've also included some test fixes from release-v0.5.0 branch so that the scripts are up-to-date for a new branch.
> Release yaml master

- openshift/release/generate-release.sh
During the release process, we use different input files, and pipe them to a larger "release" file.
after the "release" yaml file has reached final state, let's remove the bits that are not really needed
> remove files from release generation

- Makefile
- openshift/ci-operator/knative-images/sources_controller/Dockerfile
- openshift/release/generate-kafka.sh
- openshift/release/generate-release.sh
- openshift/release/resolve.sh
- openshift/release/update-to-head.sh
@syedriko @lberk   updating the `master` with relevant changes for the `release-next` branch
See similar PR:
https://github.com/openshift/knative-eventing/pull/96
EXCEPT: we do NOT stash the release yaml on master
> New image rename and better release resolve

- openshift/e2e-tests-openshift.sh
This works around the issues with Istio sidecars and OCP 4.1 by just disabling the mesh sidecars for now.
> Update Maistra to 0.10 and disable sidecar injection

- openshift/e2e-tests-openshift.sh
This installs Knative Serving via our Operator instead of using upstream Knative Serving. And, it reduces the footprint of the Istio installed to the minimal required.
> Install Knative Serving via Operator and minimal Istio

- openshift/olm/knative-eventing.catalogsource.yaml
See https://github.com/openshift-knative/knative-eventing-operator/commit/a309f5ac20b9b3d51a4d96374ade2bb8594317c4 
porting this here, since the generated `CS` is stored here ...
@lberk
> Remove the KnativeServing dep and rely on OwnerRef to show resources

- openshift/e2e-tests-openshift.sh
porting changes from to master: 
https://github.com/openshift/knative-eventing/pull/141
once merged: we use the 0.6.0 operator
tests failures on the master, are true e2e fails, unrelated to the changes
> Using 0.6.0 for next release

- Makefile
- openshift/ci-operator/knative-images/imc-controller/Dockerfile
- openshift/ci-operator/knative-images/imc-dispatcher/Dockerfile
this is porting #150 to master
From master the new/nightly `release-next` is created, hence things tested against `release-next` need to go to MASTER in order to be persistent
> correcting new imc image locations

- openshift/e2e-tests-openshift.sh
Fixing the waiting loops because the old "timeout" function disappeared. This will fix the nightly job.
Should I also send this against master?
> Fix OpenShift Conformance test suite

- openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-test-images/helloworld/Dockerfile
Since `release-next` is created _nightly_ and "openshift specific" files are added from master, I am adding dockerfiles for two more test images
However... they seem to be on the `release-next` branch already... 
@alanfx @lberk any thoughts ?
> adding missing test images

- openshift/release/create-release-branch.sh
When creating the new release branch, we already generate our release yaml for CORE - but we should also do the same for kafka
@lberk
> release creation prep work

- openshift/release/knative-eventing-v0.7.0.yaml
@lberk based on the e2e test-failure of the nightly (a test for sequences was added to master), I see that RBAC was missing.
here is the snippet:
```
tracker.go:128: Waiting for e2e-stepper1 to be deleted
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x173a57e]
goroutine 88 [running]:
testing.tRunner.func1(0xc0002d0a00)
/usr/local/go/src/testing/testing.go:830 +0x69d
panic(0x18ad100, 0x28f7e30)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/knative/eventing/test/base.GetAddressableURI(0x1c11000, 0xc0000105b0, 0xc000c3bb20, 0x0, 0x1, 0x90, 0x184a7e0)
/go/src/github.com/knative/eventing/test/base/resource_inspecto …
```
> Patching RBAC fix to our 'vendor,ed' image/release yaml

- openshift/e2e-tests-openshift.sh
Patching our operator's filename, to use the CI yaml which contains images we build during _this_ process
> patch the operator, per build

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
Update master's ConfigMap CatalogSource to the CSVs in the released versions in https://github.com/operator-framework/community-operators/tree/master/community-operators/knative-eventing-operator
Should fix SRVKE-117 (add the missing --filename arg so that CI can actually uses the CI configuration)
> SRVKE-117 update cm catalogsource to released versions

- openshift/release/knative-eventing-v0.7.1.yaml
Here is the PR to patch the yaml, by adding the `NetworkPolicy` at the end of the "productized" yaml bag
/assign @maschmid
> Adding NetworkPolicy workaround for webhook

- openshift/release/knative-eventing-kafka-v0.7.1.yaml
Adding `NetworkPolicy` cfg for the `kafka-webhook`. 
This is the file that the kafka-operator points to 
/assign @maschmid 
/assign @lberk
> adding fix for kafka-webhook

- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-v0.8.0.yaml
Fix for https://jira.coreos.com/browse/SRVKE-183 - on 0.8.0 release branch
> Adding finalizer RBAC for generic channel

- Makefile
- openshift/ci-operator/generate-ci-config.sh
we sould generate 4.3 and 4.2 - not just 4.2 cfg
> reflect multiple OCP runs

- openshift/e2e-tests-openshift.sh
upstream changed to that new group, which our serverless operator now uses for `KnativeServing` too
(while the old seems still supported)
> Go with the new APIGroup for the Knative Serving install

- config/500-webhook-configuration.yaml
- openshift/e2e-tests-openshift.sh
- openshift/release/knative-eventing-v0.12.0.yaml
The sinkbindings are too overreaching, blocking even infrastructure deployments when the webhook is down.
> SRVKE-308 failurePolicy: Ignore for sinkbindings webhooks

- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
- openshift/ci-operator/knative-images/channel_broker/Dockerfile
- openshift/ci-operator/knative-images/channel_controller/Dockerfile
- openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/cronjob_receive_adapter/Dockerfile
- openshift/ci-operator/knative-images/filter/Dockerfile
- openshift/ci-operator/knative-images/ingress/Dockerfile
- openshift/ci-operator/knative-images/ping/Dockerfile
- openshift/ci-operator/knative-images/pong/Dockerfile
- openshift/ci-operator/knative-images/sendevent/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/ci-operator/knative-test-images/eventdetails/Dockerfile
- openshift/ci-operator/knative-test-images/filterevents/Dockerfile
- openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-test-images/logevents/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/sendevents/Dockerfile
- openshift/ci-operator/knative-test-images/sequencestepper/Dockerfile
- openshift/ci-operator/knative-test-images/transformevents/Dockerfile
Part of removing the CI references, is here:
* update all images for current eventing on master/stash branch
* use better `FROM` on dockerfile to avoid CI registry hard coded
> EVenting image updates

- openshift/ci-operator/source-image/Dockerfile
Same as https://github.com/openshift/knative-eventing/pull/608, just for 0.14 branch
Will be used in openshift/release#9455
> Dockerfile for source image

- openshift/e2e-tests-openshift.sh
CI fails, b/c we do still invoke the tests w/ the _REMOVED_ `v1alpha1` APIs
> Remove the messaging v1alpha1 API invocation

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
* remove redundant env variables
* move sourcing upstream e2e-commons out from our e2e-common
* hardcode TEST_IMAGE_TEMPLATE in e2e-tests.sh as this file only runs in
CI
* move selecting TEST_IMAGE_TEMPLATE into e2e-tests-local.sh as this is
where we want to specify custom templates
* use ${variable:-} pattern where possible to prevent errors in
serverless-operator repo where we run with -e and undefined variables
fail the whole build
Please review, the same PR was sent against release-next branch here: https://github.com/openshift/knative-eventing/pull/672
> Modify scripts to be reusable in serverless-operator repo

- openshift/e2e-common.sh
- openshift/olm/knative-eventing.catalogsource.yaml
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-channelbroker-ci.yaml
- openshift/release/knative-eventing-ci.yaml
- openshift/release/resolve.sh
script produced urls that had a prefix of `gcr.io/knative-releases` drop and fix image names
> Update channel broker image urls/names

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
This PR includes commits cherry-picked from https://github.com/openshift/knative-eventing/pull/671 . It's the same PR, just against 0.15.2
> Modify scripts for reusing v0.15.2

- Makefile
- openshift/ci-operator/knative-images/migrate/Dockerfile
Similar to https://github.com/openshift/knative-serving/pull/516.
> [RELEASE-v0.15.2] Add storage version migration image.

- openshift/e2e-tests-openshift.sh
- test/e2e/parallel_test.go
- test/e2e/sequence_test.go
see: https://issues.redhat.com/browse/SRVKE-472
relates to: https://github.com/openshift/knative-eventing/pull/692
> SRVKE-472: reenable flows e2e tests 

- openshift/ci-operator/update-ci.sh
@matzew changes that resulted in openshift ci config in: openshift/release#10702
> Drop OCP 43 and 44 from nightly ci

- openshift/e2e-common.sh
- openshift/patches/012-skip-tracing-conformance.patch
- openshift/release/update-to-head.sh
However, we TEMPORARY skip the two tracing related tests
was tested with: #764
> Adding conformance test for OCP run

- openshift/patches/013-sinkbinding_webhook_corrections.patch
- openshift/patches/014-sinkbinding_tests_skip.patch
- openshift/release/generate-release.sh
As expected here: https://github.com/openshift/knative-eventing/pull/760/commits/68e18096ee7f2051300f8d5bc5a448345846e305
(see https://github.com/openshift/knative-eventing/pull/760)
the config does cause test failures.
* apply a patch to the nightly for the webhook cfg of the sinkbinding
* skip tests that are EXPECTED to fail w/ this cfg
On the road I fixed a little script error, that adds the content twice to the MT-Channel-Broker yamls
> Apply sink binding config

- openshift/e2e-common.sh
Sometimes we face races during strimzi install. See the error log:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_knative-eventing/772/pull-ci-openshift-knative-eventing-release-next-45-e2e-aws-ocp-45/1295589721136697344
```
...
openshift/e2e-common.sh: line 58: header_text: command not found
+ kubectl -n kafka apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.19.0/examples/kafka/kafka-persistent-single.yaml
error: unable to recognize "https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.19.0/examples/kafka/kafka-persistent-single.yaml": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta1"
+ header_text 'Waiting for Strimzi to become ready'
...
```
and …
> Adding CRD install label first, to avoid race

- openshift/ci-operator/update-ci.sh
we need at least one "promotion" branch
/assign @lberk
> Fixing the disabled image promotion for all branches

- openshift/ci-operator/build-image/Dockerfile
Like on `release-next` and the `release-014....` branches, we need the `httpd-tools` to install/build the Serverless Operator 1.8 (and later)
> [0.16] Updating linux container to have httpd-tools

- openshift/ci-operator/build-image/Dockerfile
Like on `release-next` and the `release-014....` branches, we need the `httpd-tools` to install/build the Serverless Operator 1.8 (and later)
> [0.15] Updating linux container to have httpd-tools

- config/core/deployments/webhook.yaml
- openshift/patches/013-sinkbinding_webhook_corrections.patch
- openshift/release/knative-eventing-ci.yaml
- test/conformance/broker_tracing_test.go
- test/conformance/channel_tracing_test.go
- test/e2e/source_sinkbinding_v1alpha1_test.go
- test/e2e/source_sinkbinding_v1alpha2_test.go
- test/e2e/source_sinkbinding_v1beta1_test.go
In #792 we add some logic to apply carried patches to newly createsd RELEASE branches (for release-next we do that every night)
Now, this PR does a _manual_ apply of those patches
> Apply carried patches.

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
* the openshift/e2e-commons.sh script is reused in other repos (e.g.
sererless-operator) which doesn't have the test/e2e-common.sh from
Eventing available
* we source only helper functions from test-infra that are commons to
all our forks and also to serverless-operator
* add explicit fail via set -e that will show which variables are
undefined
* the result of this is that we might need to define variables in
openshift/e2e-common.sh more frequently because we're not reusing
anything from test/e2e-common.sh
> Do not source test/e2e-common.sh

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
* the openshift/e2e-commons.sh script is reused in other repos (e.g.
sererless-operator) which doesn't have the test/e2e-common.sh from
Eventing available
* we source only helper functions from test-infra that are commons to
all our forks and also to serverless-operator
* add explicit fail via set -e that will show which variables are
undefined
* the result of this is that we might need to define variables in
openshift/e2e-common.sh more frequently because we're not reusing
anything from test/e2e-common.sh
> Do not source test/e2e-common.sh - master

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
* the openshift/e2e-commons.sh script is reused in other repos (e.g.
sererless-operator) which doesn't have the test/e2e-common.sh from
Eventing available
* we source only helper functions from test-infra that are commons to
all our forks and also to serverless-operator
* add explicit fail via set -e that will show which variables are
undefined
* the result of this is that we might need to define variables in
openshift/e2e-common.sh more frequently because we're not reusing
anything from test/e2e-common.sh
> Do not source test/e2e-common.sh - release-v0.17.2

- test/lib/duck/resource_checks.go
> Port 4093 to our 0.16

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
getting in the 4116 from upstream
> backporting fix for default exponential backoff calculation (#4116)

- openshift/ci-operator/generate-ci-config.sh
* migrate image should be called storage-version-migration
* adding periodic test hook
> adding migrator image change, and adding periodic test hook

- openshift/patches/015-sinkbinding_v1_tests_skip.patch
This bascially will ensure we always patch the newly added (upstream) v1 test for sinkbinding.
See https://github.com/openshift/knative-eventing/pull/886  as well
/hold
/assign @lberk
> Adding one more sinkbinding test to the list of skipped tests

- openshift/ci-operator/update-ci.sh
With 1.11 (which is 0.17) SERVERLESS we start to default to 4.6
Therefore removing the need fro 4.5 on our future releases
/assign @lberk
> Removing 4.5 channel, we are defaulting to 4.6

- openshift/e2e-common.sh
- openshift/patches/016_TestChannelChainV1beta1.patch
> fixing the namespace problem for config-tracing and removing upstream flake

- test/lib/recordevents/recorder_vent/constructor.go
> Publish manually events to avoid event correlator (#4373) (#4386)

- test/lib/dropevents/receiver.go
- test/lib/recordevents/event_info.go
- test/lib/recordevents/logger_vent/logger.go
- test/lib/recordevents/observer/observer.go
- test/lib/recordevents/recorder_vent/constructor.go
- test/lib/recordevents/recorder_vent/recorder.go
- test/lib/test_runner.go
- test/test_images/recordevents/main.go
Ported:
- https://github.com/knative/eventing/pull/4393
- https://github.com/knative/eventing/pull/4389
- https://github.com/knative/eventing/pull/4385
> Port recordevents updates

- test/upgrade/README.md
- test/upgrade/probe_test.go
- test/upgrade/prober/config.toml
- test/upgrade/prober/configuration.go
- test/upgrade/prober/forwarder.go
- test/upgrade/prober/prober.go
- test/upgrade/prober/prober_test.go
- test/upgrade/prober/receiver.go
- test/upgrade/prober/sender.go
Cherry-picked PRs:
* knative#3899
* knative#4421 (not yet merged)
> Backport wathola configurability

- test/upgrade/prober/configuration.go
- test/upgrade/prober/forwarder.go
- test/upgrade/prober/prober_test.go
- test/upgrade/prober/receiver.go
- test/upgrade/prober/sender.go
* Embedding configuration structs 40cf183a024cf004f855a68d256c2729dea06855 commit from PR https://github.com/knative/eventing/pull/4421
This is required to complete https://github.com/openshift-knative/serverless-operator/pull/530
> Backport of 4421 review changes

- test/upgrade/probe_test.go
Backporting PR knative#4442 to [release-v0.17.2 branch](https://github.com/openshift/knative-eventing/tree/release-v0.17.2).
This is required by https://github.com/openshift-knative/serverless-operator/pull/530#issuecomment-717367653
> [release-v0.17.2] Backport: PR 4442

- test/upgrade/prober/receiver.go
- test/upgrade/prober/sender.go
This is a possible backport of upstream PR knative#4445. That depends on that upstream PR being merged. I think there's a good chance for it to happen.
If upstream PR will be merged, then nothing more isn't required for 0.18+.
Otherwise, this PR must be also converted to a patch on master branch. Then it must be applied on each release-next, until a better solution is found.
This is required for openshift-knative/serverless-operator#530 (comment)
> [release-v0.17.2] Hotfix: Use deployment to avoid disparity in effective user

- test/upgrade/prober/forwarder.go
- test/upgrade/prober/kservice.go
- test/upgrade/prober/prober.go
- test/upgrade/prober/receiver.go
- test/upgrade/prober/verify.go
This is a possible backport of upstream PR knative#4430. That depends on that upstream PR being merged. I don't give a huge confidence that happening.
If upstream PR will be merged, then nothing more isn't required for 0.18+. 
Otherwise, this PR must be also converted to a patch on master branch. Then it must be applied on each release-next, until a proper fix for knative#3175 is provided.
This is required for https://github.com/openshift-knative/serverless-operator/pull/530#issuecomment-717367653
> [release-v0.17.2] Hotfix: Deploying receiver as ksvc if serving is available

- test/upgrade/prober/prober.go
The 0.17.x line of upstream is still using pre 1.18 K8s dependencies, so there's no value in passing the context around everywhere just yet.
/assign @matzew @cardil
> Fix compilation error by removing bad merge

- openshift/e2e-tests.sh
As per title. This compiles the entire repo (including tests we don't run in CI), to make sure there are no compilation errors missed in CI.
> Add a compilation check to the CI run to catch issues in PRs

- cmd/mtbroker/ingress/main.go
- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- pkg/kncloudevents/http_client.go
- pkg/kncloudevents/http_client_test.go
- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/mtbroker/filter/filter_handler_test.go
- pkg/mtbroker/ingress/ingress_handler.go
- pkg/reconciler/apiserversource/resources/receive_adapter.go
- pkg/reconciler/apiserversource/resources/receive_adapter_test.go
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
- test/conformance/broker_tracing_test.go
- test/conformance/channel_tracing_test.go
Backport of:
* https://github.com/knative/eventing/pull/4472
* https://github.com/knative/eventing/pull/4457
* https://github.com/knative/eventing/pull/4468
* https://github.com/knative/eventing/pull/4471
* https://github.com/knative/eventing/pull/4480
* https://github.com/knative/eventing/pull/4483
and, like on 0.18.3: skip traces (they are enabled on `release-next`)
> Backports and skip tracing 

- openshift/e2e-common.sh
Using Serverless 1.11 branch, and just install serving with it
> Run the install with the base of 1.11 product

- openshift/e2e-common.sh
unset OPENSHIFT_CI , so that we use currently promoted CI images for the serverless operator
> unset OPENSHIFT_CI

- openshift/e2e-common.sh
unset OPENSHIFT_CI so we use currently promoted CI images for the serverless operator
> Backport #973 to 0.18.4

- pkg/reconciler/source/crd/crd.go
- pkg/reconciler/source/crd/crd_test.go
related: [SRVKE-632](https://issues.redhat.com/browse/SRVKE-632)
knative.dev/pkg controller runtime doesn't allow for global level
resync and leaderelection functions to filter out objects set by
filter funcs.  In the case of the crd controller -- this means our
reconciliation process picks up unrelated objets to try and create
duck controllers.  Add an extra check in the reconcile process
equivalent to the informer filterFunc
> source.crd controller: filter out non duck crds

- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
As title says.
This follow up on #982 and it's required for openshift-knative/serverless-operator#697
> Dockerfile for wathola-fetcher test image

- Makefile
- openshift/ci-operator/knative-images/chaosduck/Dockerfile
Adding dockerfile for the chaos duck
See also: https://github.com/openshift/release/pull/13827
> [0.18] Adding Chaosduck image

- openshift/ci-operator/update-ci.sh
Adding back the script that adds the (relevant) images to the mirror file. Instead of doing this manually....
However, we only need the "test" images... not the "core" images
/assign @lberk 
BTW.  I used this to generate https://github.com/openshift/release/pull/13893
> [0.19] Adding back the image mirror, but only for test images.

- config/core/deployments/pingsource-mt-adapter.yaml
- pkg/adapter/v2/config.go
- pkg/adapter/v2/config_test.go
This is a backport of a fix from Lionel (fix crash when pingsource adapter is scaled up without any sources (#4242))
> [0.18] backport of upstream 0.19+ fix

- config/channels/in-memory-channel/deployments/dispatcher.yaml
- openshift/release/knative-eventing-ci.yaml
> [0.19.2] Porting 4640 to OCP

- openshift/ci-operator/update-ci.sh
next time we run `make update-ci` we _automatically get the 4.7 OCP CI runs.....
> [HEAD] Adding 4.7 CI generator script

- openshift/ci-operator/update-ci.sh
next time we run `make update-ci` we _automatically get the 4.7 OCP CI runs.....
CURRENTLY: we added that manually.......
> [0.19] Adding 4.7 CI generator script

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
on the 0.19.1 we have this.
Moving here, to the stash, so we have it on all new branches...
> Adding teardown to master_stash

- test/e2e/broker_with_many_triggers_test.go
skipping a test that only fails on OCP 4.7, since DEC 16th (without any modification on our end)
> [0.19.2] Skip a test

- go.mod
- go.sum
- vendor/knative.dev/pkg/metrics/config.go
- vendor/knative.dev/pkg/metrics/exporter.go
- vendor/knative.dev/pkg/metrics/prometheus_exporter.go
- vendor/modules.txt
backport from @skonto of https://github.com/knative/eventing/commit/c98493db70cb53097f3e7d38111012fccf6a6843
> [0.19.2] backport: add prom host (#4661)

- openshift/patches/017-brokerManyTestsSpecificWaits.patch
Checking to see if CI runs need to have more explicit waits on each resource
> TestBrokerWithManyTriggers - add specific waits on resources patch

- openshift/release/mirror-upstream-branches.sh
This script will check the upstream remote branches, and if there are
new ones (assuming a new release), mirror those to the 'midstream'
openshift forks
note, this doesn't yet run `make update-ci`.
> Add mirror-upstream-branches.sh script

- openshift/ci-operator/build-image/Dockerfile
Upstream did bump to 1.15 [earlier today](https://github.com/knative/eventing/pull/4795/commits/e69815dda133e27190835874eef203af1305369d) on `HEAD`, doing same here
Our serving fork also uses the 1.15 as the base since a few days
> Using 1.15 on our linux container

- openshift/release/update-to-head.sh
Most runs this should return 0 (and no error) as we have no new
upstream branches to mirror
> Run mirror-to-upstream-branch.sh script from nightly mirror

- test/upgrade/upgrade.go
- test/upgrade/upgrade_test.go
This will be required for upgrades in serverless-operator. Without this patch the variable `channelTestRunner` is not accessible.
This change should be there automatically when we pull 0.21.x branch from upstream.
> Expose runmaintest for upgrades

- pkg/adapter/mtping/runner.go
https://github.com/knative/eventing/issues/5058
Signed-off-by: rickr <cr22rc@users.noreply.github.com>
/hold
> [0.21 backport] Timezone not added to schedule in runner.go #5058 (#5059)

- pkg/adapter/mtping/runner.go
https://github.com/knative/eventing/issues/5058
Signed-off-by: rickr <cr22rc@users.noreply.github.com>
/hold
> [0.20 backport] Timezone not added to schedule in runner.go #5058 (#5059)

- openshift/ci-operator/build-image/kubernetes.repo
This is a fix according to kubernetes/kubernetes#60134 . The build image includes GnuPG 2.0.22 which shows this problem.
> [0.20] Disable repo_gpgcheck for kube repo in build image

- openshift/e2e-common.sh
> Upstream did drop the v1beta, correcting our test execution for channels

- openshift/patches/014-sinkbinding_tests_skip.patch
was done as part of this commit, see: https://github.com/knative/eventing/pull/5317
> Upstream removed the v1alpha1 tests

- vendor/knative.dev/pkg/controller/stats_reporter.go
- vendor/knative.dev/pkg/webhook/stats_reporter.go
Shutdown these noisy metrics (they are in TODO status because they are useful), however I spotted a worse issue. Check my comment [here](https://github.com/knative/serving/issues/11248#issuecomment-826380392). 
/cc @matzew  @schmidtd.
> [SRVKS-720] Mute noisy metrics controller & webhook

- openshift/patches/014-sinkbinding_tests_skip.patch
see: https://github.com/knative/eventing/pull/5318
> Upstream removed the v1alpha2 tests

- openshift/e2e-common.sh
the enabling traces still uses the `header_text`, instead of `logger.info` calls
> Using logger.info instead of header_text

- openshift/e2e-common.sh
> [0.20] Use the latest of OCP Serverless on 0.20 branch

- openshift/e2e-common.sh
> [0.22] Use the latest of OCP Serverless on 0.22 branch

- openshift/e2e-common.sh
> [0.21] Use the latest of OCP Serverless on 0.21 branch

- openshift/e2e-common.sh
bringing #1240 to `main` branch
> [main] using logger.info instead of header_text (#1240)

- openshift/e2e-common.sh
bringing #1240 to `0.22` branch
> [0.22] using logger.info instead of header_text (#1240)

- Makefile
for REKT TEST, we need the `eventhub` image
> Adding the eventhub image to the list of test images

- openshift/e2e-common.sh
> [main] Use the latest of OCP Serverless on main branch

- openshift/e2e-common.sh
was done via upstream PR #5319
> Removing the beta source APIs

- openshift/patches/019-remove-tracing-observability-yamls.patch
- openshift/release/generate-release.sh
Getting back the IMC content... after symlnks got removed upsream
also removing the duplicated tracing/observabilty yamls
> [main] Imc generation patch

- test/upgrade/prober/forwarder.go
As per title. This fixes the wrong label for cluster-local services and unblocks serverless-operator CIs upgrade tests.
> [RELEASE-v0.22.0] Use new label for defining a cluster-local Knative Service

- test/upgrade/prober/forwarder.go
As per title. This fixes the wrong label for cluster-local services and unblocks serverless-operator CIs upgrade tests.
> [RELEASE-v0.21.0] Use new label for defining a cluster-local Knative Service

- openshift/ci-operator/build-image/Dockerfile
Bump to go 1.16 (see: https://github.com/knative/eventing/pull/5359/files)
> Using 1.16 on our linux container

- vendor/knative.dev/pkg/webhook/certificates/certificates.go
- vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
- vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
> [0.22] Rollback certificate algorithm changes (#1281)

- test/upgrade/prober/sut/broker.go
- test/upgrade/prober/sut/broker_e2e_test.go
Backport of knative#5444
* Don't wait on triggers, before deploying their subscriber
> [0.21] Backport of knative#5444

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
We will create CI config for `release-v X.Z` branches, but start the promotion with `release-v X.Y.Z` due to the coupling of the "upstream manifest" download on the serverless operator.
* `generate-ci-config.sh` the branch name (e.g. `release-v0.23`) is used as promotion name, with a static `.0` at the end (to match the upstream version schema, b/c: https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/project.yaml#L29
* `update-ci.sh ` the script to trigger `make update-ci` checks the name of the branch, and was complaining about the new format (e.g. `releaes-0.23`)
> Fixing some scripts for 0.23 (and later)

- openshift/patches/018-rekt-test-apiserversource_data_plane.patch
There was a new ko-image reference added in https://github.com/knative/eventing/pull/5348
On OCP we are not using `ko apply`, so we have to replace the `ko://` references with our own images.
The `print` image does already exist on our registry, b/c it's older, so we can just replace it. We do NOT need to setup up an extra image build etc
/assign @lberk
/cc @aliok
> A new image to replace

- openshift/patches/018-rekt-test-skip-TestEventTransformationForSubscriptionV1.patch
To get a working `release-next` we stash this patch to `main`.
We have a ticket for [SRVKE-825](https://issues.redhat.com/browse/SRVKE-825) to get the test working, on OCP, again
> Adding temporary fix to skip one REKT test for futher investigations

- openshift/patches/020-mutemetrics.patch
- use a patch until there is a fix upstream.
- original fix [here](https://github.com/openshift/knative-eventing/pull/1223).
> [main] Mute noisy metrics patch next

- openshift/patches/020-mutemetrics.patch
- vendor/knative.dev/pkg/controller/stats_reporter.go
- vendor/knative.dev/pkg/webhook/stats_reporter.go
- use a patch until there is a fix upstream.
- original fix [here](https://github.com/openshift/knative-eventing/pull/1223).
> [release-22] Mute noisy metrics patch 

- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
As per title - we should not use nightly here
> Align the rekt test for 0.23 with the version images from the registry

- openshift/patches/020-mutemetrics.patch
- vendor/knative.dev/pkg/controller/stats_reporter.go
- vendor/knative.dev/pkg/webhook/stats_reporter.go
- use a patch until there is a fix upstream.
- original fix [here](https://github.com/openshift/knative-eventing/pull/1223).
> [release-23]  mute noisy metrics patch

- openshift/ci-operator/generate-ci-config.sh
The `make update-ci` _TARGET_ generates the config for the `openshift/release` repo.
Recently we have increased the default timeout to 4h:
https://github.com/openshift/release/commit/6c3b6e796434f8612f3ac4b543741d31e3f24fb8
This adds those values directly to the generator script
> Adding timeput for e2e jobs to the generator script

- pkg/channel/fanout/fanout_message_handler.go
- pkg/channel/stats_reporter.go
Backport of: https://github.com/knative/eventing/pull/5478 & https://github.com/knative/eventing/pull/5481
/cc @matzew
> [Release-v0.22.0][Backport] Make Channel metrics generic enough for eventing-kafka

- pkg/channel/fanout/fanout_message_handler.go
- pkg/channel/message_dispatcher.go
- pkg/channel/stats_reporter.go
Same as in #1316, cherry picked the related commits from main upstream. I will the create a PR against eventing-kafka 0.23, this is for aligning the code bases.
> [Backport] [Release 0.23] Use transformers to extract metrics for Kafka

- openshift/release/mirror-upstream-branches.sh
catch branches on openshift that match v0.X and the previous v.X.Y scheme
> Update mirroring script branch check due to new naming scheme

- Makefile
- openshift/patches/018-rekt-test-override-kopublish.patch
adding one more patch to get REKT tests on OCP to work
> Return rekt tests

- vendor/knative.dev/reconciler-test/pkg/images/ko.go
Bringing patch to 0.24 that was done on `main`/`release-next` .....
See https://github.com/openshift/knative-eventing/pull/1341
> Patch the rekt for 0.24 too

- test/conformance/README.md
- test/conformance/broker_tracing_test.go
- test/conformance/channel_addressable_resolver_cluster_role_test.go
- test/conformance/channel_channelable_manipulator_cluster_role_test.go
- test/conformance/channel_crd_metadata_test.go
- test/conformance/channel_tracing_test.go
- test/conformance/create-namespace-rbac.sh
- test/conformance/main_test.go
- test/conformance/source_crd_metadata_test.go
- test/conformance/source_crd_rbac_test.go
- test/conformance/source_crd_registry_test.go
- test/lib/creation.go
- test/lib/recordevents/resources.go
- test/lib/setupclientoptions/sources.go
- test/lib/test_runner.go
Backporting the exact same commit from upstream.
> [release-v0.24] Backport of run conformance tests as project admin

- test/conformance/README.md
- test/conformance/broker_tracing_test.go
- test/conformance/channel_addressable_resolver_cluster_role_test.go
- test/conformance/channel_channelable_manipulator_cluster_role_test.go
- test/conformance/channel_crd_metadata_test.go
- test/conformance/channel_tracing_test.go
- test/conformance/create-namespace-rbac.sh
- test/conformance/main_test.go
- test/conformance/source_crd_metadata_test.go
- test/conformance/source_crd_rbac_test.go
- test/conformance/source_crd_registry_test.go
- test/e2e/main_test.go
- test/e2e_flags.go
- test/flags/eventing_environment.go
- test/lib/creation.go
- test/lib/recordevents/resources.go
- test/lib/setupclientoptions/sources.go
- test/lib/test_runner.go
Backporting commits that make it possible to run coformance tests as a project admin user.
> [release-v0.23] Backports for conformance tests

- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Done for [SRVKS-790]. See https://github.com/openshift/knative-eventing/pull/1361 for reference
> [0.25] Patch subresource to unblock webhooks on 4.9 (#1361)

- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Done for [SRVKS-790]. See https://github.com/openshift/knative-eventing/pull/1361 for reference
> [0.24] Patch subresource to unblock webhooks on 4.9 (#1361)

- openshift/ci-operator/generate-ci-config.sh
- openshift/e2e-common.sh
- openshift/e2e-conformance-tests.sh
- openshift/e2e-rekt-tests.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
Should be merged together with https://github.com/openshift/release/pull/21286
It's a sibling of https://github.com/openshift/knative-eventing/pull/1377
*    IMAGE_FORMAT variable is not available when using cluster pools, images are passed explicitly by CI operator, this approach is already used by openshift/knative-serving
*    Removed scaling up the cluster. I tested without scaling and all tests passed anyway so it's not required anymore.
> [release-v0.24] Prepare for cluster pools

- openshift/ci-operator/generate-ci-config.sh
- openshift/e2e-common.sh
- openshift/e2e-conformance-tests.sh
- openshift/e2e-rekt-tests.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
Includes changes from https://github.com/openshift/knative-eventing/pull/1378 and https://github.com/openshift/knative-eventing/pull/1384 , only for main branch
* IMAGE_FORMAT variable is not available when using cluster pools, images are passed explicitly by CI operator, this approach is already used by openshift/knative-serving
* Removed scaling up the cluster. I tested without scaling and all tests passed anyway so it's not required anymore.
* Generate CI config for cluster-pools
> [main] Prepare for cluster pools (remove IMAGE_FORMAT, generate cluster-pool)

- openshift/patches/005-subresource.patch
as per title - similar to https://github.com/openshift/knative-eventing/pull/1361 (as on main)
> Adding patch for OCP 4.9, like done on older release branches (0.24+)

- openshift/e2e-common.sh
- openshift/e2e-conformance-tests.sh
- openshift/e2e-rekt-tests.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
Fixes the script failures in https://github.com/openshift-knative/serverless-operator/pull/1153
-
-
-
**Release Note**
```release-note
```
**Docs**
> [release-v0.24] Do not set TEST_IMAGE_TEMPLATE in e2e-commons.sh

- openshift/e2e-common.sh
- openshift/e2e-conformance-tests.sh
- openshift/e2e-rekt-tests.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
This file is sourced in serverless-operator repo and setting
TEST_IMAGE_TEMPLATE would override the same variables that is set
differently in serverless-operator.
Same as https://github.com/openshift/knative-eventing/pull/1394 , only for main branch.
> [main] Do not set TEST_IMAGE_TEMPLATE in e2e-commons.sh

- openshift/ci-operator/generate-ci-config.sh
Needs to be cherry picked to at least agains:
* 0.25
* 0.24
* 0.23
* 0.22
(older brnaches are likely not that often updated ...)
> [main] Adding dptp change to job config generator

- config/core/resources/trigger.yaml
- test/experimental/delivery_timeout_test.go
- test/rekt/features/broker/readyness.go
- test/rekt/resources/broker/broker.go
- test/rekt/resources/broker/broker.yaml
- test/rekt/resources/delivery/delivery.go
- test/rekt/resources/trigger/trigger.go
- test/rekt/resources/trigger/trigger.yaml
Signed-off-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
Co-authored-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
@devguyio I'd like to port this change from @pierDipi to here.
Once that is merged, I'd like to bump tthis to 0.25.1  
https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/project.yaml#L29
and change the image promotion on `openshift/release` for the 0.25.0 CI job to be also 0.25.1
> [release-v0.25] Backport: DeliverySpec.Timeout on Broker and Trigger (#5689)

- openshift/e2e-common.sh
with this we are aligned like here:
https://github.com/openshift-knative/serverless-operator/blob/18b4a322177bb28fb910614d4eedde8b324096df/hack/lib/tracing.bash#L43
/assign @cardil
> [main] Go with latest for zipkin... same like on Serverless Product repo

- openshift/e2e-common.sh
> Use version ghcr for zipkin:2

- go.mod
- go.sum
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/knative.dev/pkg/webhook/configmaps/configmaps.go
- vendor/knative.dev/pkg/webhook/json/decode.go
- vendor/knative.dev/pkg/webhook/psbinding/psbinding.go
- vendor/knative.dev/pkg/webhook/resourcesemantics/defaulting/defaulting.go
- vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
- vendor/modules.txt
Updating the `knative.dev/pkg` with the "proper" fix for allow unknown metadata fields.
The PR contains two different actions.
* Revert of https://github.com/openshift/knative-eventing/pull/1365
* Cherry-pick of the upstream (release-0.24) PR (https://github.com/knative/eventing/commit/c63ace359c3f0c4fbd2e5ce82cc5f28d9da8cd06) to pick the updates for https://github.com/knative/pkg/pull/2255
> [release-v0.24] allow unknown metadata fields

- openshift/patches/005-k8s-min.patch
Bringing https://github.com/openshift/knative-eventing/pull/1470  to main stash....
> Vendor serving's k8s min version patch

- openshift/patches/021-rekt-skip-test-trigger.patch
To unblock the failures, I am skipping issue is tracked in [SRVKE-1046](https://issues.redhat.com/browse/SRVKE-1046)
> Patching a test to skip it, tracked as SRVKE-1046

- openshift/e2e-common.sh
as per title.
(was tested here: https://github.com/openshift/knative-eventing/pull/1516)
/assign @aliok 
/assign @pierDipi
> Update to 1.19 product build

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Manual change, to avoid conflicts wth "nightly".
Let's see that when we create a versioned branch, that we do some `sed` fu on patch files like:
https://github.com/openshift/knative-eventing/blob/main/openshift/patches/018-rekt-test-image-changes.patch#L22
So the `rekt test` images are than _matching_ the actual version....
for now... this is a manual change....
> [release-v0.26] Do not use nightly for versioned branch

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Manual change, to avoid conflicts wth "nightly".
Let's see that when we create a versioned branch, that we do some `sed` fu on patch files like:
https://github.com/openshift/knative-eventing/blob/main/openshift/patches/018-rekt-test-image-changes.patch#L22
So the `rekt test` images are than _matching_ the actual version....
for now... this is a manual change....
> [release-v1.0] Do not use nightly for versioned branch

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Manual change, to avoid conflicts wth "nightly".
Let's see that when we create a versioned branch, that we do some `sed` fu on patch files like:
https://github.com/openshift/knative-eventing/blob/main/openshift/patches/018-rekt-test-image-changes.patch#L22
So the `rekt test` images are than _matching_ the actual version....
for now... this is a manual change....
> [release-v0.25] Do not use nightly for versioned branch

- openshift/release/create-release-branch.sh
when we create the RELEASE BRANCHES, we need the `nightly` test images to be replaced with versions.
For the REKT-TEST we have a handful of patches that override the `ko://` schema to use _real_ images.
On versioned branches, of course, we should not use `nightly`
> Patch patches to be versioned image strings

- openshift/patches/019-remove-tracing-observability-yamls.patch
Upstream changed labels: https://github.com/knative/eventing/pull/5960
reflecting on patch for midstream 
/assign @aliok
> Reflecting label changes on patch files

- openshift/e2e-common.sh
The main branch should use the main branch of the SO,
so that we catch problems sooner.
> Checkout Serverless Operator main branch

- openshift/ci-operator/generate-ci-config.sh
As per title, and tested here: https://github.com/openshift/release/pull/25439
/hold
> Remove hard-coded 4.8 version

- test/upgrade/prober/configuration.go
- test/upgrade/prober/prober.go
- test/upgrade/prober/verify.go
Backport of https://github.com/knative/eventing/pull/6074 
* Prober waits until receiver state != active or timeout
* Generate names for fetcher
* Prevent creating another job with the same name as the one that
already exist but was not deleted yet
* Pass the created name to waitForJobToComplete
* Increase jobWaitTimeout to 10 minutes
> [release-v1.0] Prober waits until receiver state != active or timeout

- openshift/release/generate-release.sh
Upstream TAGs for releases are now called `knative-vX.Y.Z`, this leads to incorrect generated CI manifests, see here:
https://github.com/openshift/knative-eventing/blob/release-v1.2/openshift/release/knative-eventing-ci.yaml#L3353
Source is that we pass in the upstream tag, when we _automatically_ create the release, see:
https://github.com/openshift/knative-eventing/blob/main/openshift/release/mirror-upstream-branches.sh#L35
Fix: remove the version from the actual generator, and be explicit on the automation (mirror-update-branches).
For manually regenerating the bits, we than need to invoke the script like:
```bash
make RELEASE=knative-v1.0.0 generate-release
```
(as an example)
Once this is merged, we need to cherry pick it to …
> Remove knative- from the release generator script

- README.md
Retire `lberk` and put `matzew` out for FEB, MAR
> Update ci duty schedule

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
Running:
```
git checkout release-v1.2
make update-ci VERSION=knative-v1.2.0 OPENSHIFT=~/redhat/openshift/release/
```
produces no changes in `openshift/release` as expected.
> Run Eventing midstream periodic jobs only on 4.9

- openshift/ci-operator/update-ci.sh
as per title
NOTE: genrating periodics for 4.10 _as well_.
We might want to change that to _only_ 4.10 (instead of 4.9 as well)
> [release-v1.2] adding generator for 4.10

- openshift/ci-operator/generate-ci-config.sh
Cherry-pick of https://github.com/openshift/knative-eventing/pull/1639
> [v1.2] Different cron times for branches for periodics (#1639)

- config/core/resources/channel.yaml
- docs/eventing-api.md
- pkg/apis/messaging/v1/channel_template_types.go
- test/rekt/channel_test.go
- test/rekt/features/channel/features.go
- test/rekt/resources/channel/channel.go
- test/rekt/resources/channel/channel_test.go
- test/rekt/resources/channel_impl/channel_impl.go
bringing #6264 to OCP midstream
FYI: https://github.com/openshift/knative-eventing/pull/1609  is already in...
> [release-v1.0] backport of 6264

- openshift/e2e-common.sh
There is no separate sugar controller anymore since it was merged
into the main controller, see
https://github.com/openshift/knative-eventing/tree/release-next/openshift/ci-operator/knative-images
> Remove sugar controller since it was merged

- openshift/e2e-common.sh
- openshift/release/generate-release.sh
For better "release artifact" yamls, we dont add test bits to our midstream manifests.
Was tested in:
https://github.com/openshift/knative-eventing/pull/1718
> Do not populare the Eventing CI files with testing bits

- openshift/e2e-common.sh
The tests are using the ARTIFACTS dir to store JUnit results so they
should be available in the job report.
> [release-v1.1] Set ARTIFACTS based on ARTIFACT_DIR provided in CI

- pkg/reconciler/parallel/resources/subscription.go
- pkg/reconciler/parallel/resources/subscription_test.go
- test/rekt/features/parallel/readyness.go
- test/rekt/smoke_test.go
Backport https://github.com/knative/eventing/pull/6405
> [1.2] Parallel to use `subscription.subscriber` instead of `reply` if there's no filter

- openshift/patches/pdb_v1beta1_unavailable_in_4.6_openshift.patch
> [main] Patch PDB to use v1beta1 since it wasn't available in 4.6

- openshift/patches/018-rekt-test-image-changes.patch
With https://github.com/knative/eventing/pull/6451 we needed to adjust a patch for two `go test` files
> Fix patch after upstream updates

- openshift/patches/018-e2e-test-so-fix-TestBrokerNamespaceDefaulting.patch
[SRVKE-1265](https://issues.redhat.com//browse/SRVKE-1265) knative-eventing e2e.TestBrokerNamespaceDefaulting downstream flake
tested on release-v1.3 in https://github.com/openshift/knative-eventing/pull/1837
> SRVKE-1265 SO specific patch for TestBrokerNamespaceDefaulting

- config/core/configmaps/sugar.yaml
- openshift/release/artifacts/eventing-core.yaml
- pkg/reconciler/sugar/trigger/trigger.go
Fixes https://issues.redhat.com/browse/SRVKE-1280
PR to repair the broker config with the new settings.
We keep the old default label `eventing.knative.dev/injection` for *Brokers* and *Triggers*, until we sunset the sugar controller in Openshift serverless 
See individual commits for details
> [release-v1.4] Patch broker sugar config on midstream

- openshift/ci-operator/build-image/Dockerfile
Golang updates:
* Updating to golang-1.18, since upstream is now building with that. Similar PR from serving team: https://github.com/openshift/knative-serving/pull/1182
* Tweaking the `go get` command, similar to what serving team did in https://github.com/openshift/knative-serving/pull/1185
> [main] Golang 1.18 bump and go-get command tweak

- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/Dockerfile_with_kodata.in
Based on https://github.com/openshift/knative-eventing/pull/1807, updating the other `Dockerfile`s.... 
Since, https://github.com/openshift/knative-eventing/pull/1852 seems to be not relevant any more.
Big question: Is the `openshift/ci-operator/build-image/Dockerfile` no longer in use? 
/assign @aliok 
/assign @pierDipi
> Using Golang 1.18

- config/core/configmaps/sugar.yaml
- openshift/release/artifacts/eventing-core.yaml
- pkg/reconciler/sugar/trigger/trigger.go
Following up on https://github.com/openshift/knative-eventing/pull/1849 - But for 1.5
We can decide if we want to patch and keep this behavior, or if for 1.5 (1.26) (or even 1.6/1.27) we want a proper `post-install` job (just for Openshift Serverless), that migrates the annotations to be labels.
But that's TBD...
> [release-v1.5] Patch broker sugar config on midstream

- openshift/patches/patch_sugar_controller_for_backwards_compat.patch
similar to https://github.com/openshift/knative-eventing/pull/1856
But for `main`, or `release-next` 
At somepoint we can revisit this, and perhaps change the support of sugar controller to be removed/deprecated
> Adding patch to keep sugar controller behavior

- config/core/configmaps/sugar.yaml
- openshift/release/artifacts/eventing-core.yaml
- pkg/reconciler/sugar/trigger/trigger.go
Following up on https://github.com/openshift/knative-eventing/pull/1849 - But for 1.6
We can decide if we want to patch and keep this behavior, or if for 1.6 (1.27) (or even 1.7/1.28) we want a proper post-install job (just for Openshift Serverless), that migrates the annotations to be labels.
But that's TBD...
> [release-v1.6] Patch broker sugar config on midstream

- Makefile
- openshift/patches/100-ko-baseimage.patch
TEST_IMAGE_TAG allows for per-branch test image build, and KO_FLAGS allows for --platform (for multi-arch builds) and --sbom=none (for quay.io uploads).
> Allow more customization of ko resolve commands

- openshift/release/artifacts/eventing-core.yaml
- openshift/release/artifacts/in-memory-channel.yaml
Midstream resources were out of sync, hence regenerating those with the `make RELEASE` target
> [release-v1.3] Regenerate release based on existing resources

- go.mod
- go.sum
- vendor/knative.dev/hack/release.sh
- vendor/modules.txt
For release 1.7.0 in upstream, some things were simply missing.
Those were added in two PRs to the upstream branch:
* https://github.com/knative/eventing/pull/6493
* https://github.com/knative/eventing/pull/6495
This PR lands those changes (resulting in upstream 1.7.1) to our midstream 1.7 branch...
> [release-v1.7] Correct the upstream 1.7 release adjustments on midstream branch

- openshift/patches/018-rekt-test-image-changes.patch
Change was needed due to:
https://github.com/knative/eventing/pull/6507
> Patching a patch for Container Source

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
As per title
__NOTE:__ For 1.7 we have _not_ enabled the CI automation, but there is IMO no harm in updating this _now_ :sweat_smile:
> [release-v1.7 Using proper versioned images for 1.7

- openshift/patches/005-k8s-min.patch
> We are supporting min OCP 4.8, which matches to upstream k8s 1.21

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- config/brokers/mt-channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/dispatcher.yaml
- config/core/deployments/controller.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- config/core/deployments/webhook.yaml
- config/post-install/storage-version-migrator.yaml
- config/tools/appender/appender.yaml
- config/tools/event-display/event-display.yaml
- config/tools/heartbeats/heartbeats.yaml
- config/tools/recordevents/recordevents.yaml
- config/tools/websocket-source/websocket-source.yaml
- openshift/release/artifacts/eventing-core.yaml
- openshift/release/artifacts/eventing-post-install.yaml
- openshift/release/artifacts/in-memory-channel.yaml
- openshift/release/artifacts/mt-channel-broker.yaml
replacing `all` with `ALL`, since this is the only acceptable string check [here](https://github.com/kubernetes/kubernetes/blob/6dbec8e25592d47fc8a8269c86d4b5fa838d320b/staging/src/k8s.io/pod-security-admission/policy/check_capabilities_restricted.go#30) and [here](https://github.com/kubernetes/kubernetes/blob/6dbec8e25592d47fc8a8269c86d4b5fa838d320b/staging/src/k8s.io/pod-security-admission/policy/check_capabilities_restricted.go#L94)
Related to https://github.com/openshift-knative/serverless-operator/pull/1773#issuecomment-1286682842
Also, please see upstream https://github.com/knative/eventing/pull/6533
> [release-v1.5] Fix scc drop issues

- openshift/patches/005-k8s-min.patch
- vendor/knative.dev/pkg/version/version.go
or 1.5 (aka 1.26 serverless), we are min at OCP 4.8 (aka k8s 1.21).
/hold 
(for feedback and reviews)
> [release-v1.5] Setting to 1.21 (matching ocp 4.8)

- config/core/deployments/webhook-hpa.yaml
- openshift/release/artifacts/eventing-core.yaml
Since we now target 4.8 -> 4.12 for OCP we must do the `v1`
> [release-v1.5] Re-patched the PDB manifest to be v1, instead of v1b1

- openshift/release/artifacts/eventing-core.yaml
Readiness hooks on manifest were forgotten to be added to the release manifests on actual backport
> [release-v1.6] Add new readiness hooks to manifest

- test/upgrade/prober/verify.go
Exporting too many traces may lead to test suite timeouts and the root cause should be common and visible with fewer event traces.
> [release-v1.5] Decrease exportTraceLimit to 100

- RELEASE.md
Fix a tiny typo (and some wording) in the RELEASE.md:
`soo` -> `soon`
> Fix tiny typo in release manual

- openshift/patches/018-rekt-test-image-changes.patch
This is to make the nightly sync job pass. Last failure was https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing/615/console
> Fix patch after upstream changes for security context

- openshift/patches/keep_hpa_v2beta2_until_ocp_4.13.patch
- openshift/patches/remove_seccompProfile.patch
* removing `seccompProfile`, since invalid for versions < 4.11
* going to `autoscaling/v2beta2` since `autoscaling/v2` not available on 4.8
/assign @pierDipi
> [main] Patches to make OCP 48 -> OCP 4.11 work

- openshift/patches/005-k8s-min.patch
Upstream bumped to 1.24 (from 1.23), so our tmp..... patch is being patched ... :dizzy:
> [main] Updating min version patch

- openshift/release/create-release-branch.sh
- openshift/release/update-to-head.sh
We have a patch file that creates a new file, but currently our "create branch" scripts are not adding that newly created file to the tree, since it does `git apply`, like:
```
➜  eventing git:(xyz) git apply openshift/patches/022-openshift-serverless-view-eventing-configmaps.patch 
➜  eventing git:(xyz) ✗ gst
HEAD detached from upstream/main
Untracked files:
(use "git add <file>..." to include in what will be committed)
config/openshift-serverless-view-eventing-configmaps.yaml
nothing added to commit but untracked files present (use "git add" to track)
```
With `--index` the file is added:
```
it apply --index openshift/patches/022-openshift-serverless-view-eventing-configmaps.patch
➜  eventing git:(xyz) ✗ gst
HEAD detached from …
```
> Make sure we also new files, created out of the git-apply command
