openshift/knative-eventing

- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/build-image/kubernetes.repo
Add Build image for OpenShift CI
> Build image master

- openshift/kubecon-demo.sh
If this passes then it will replace the other PR from Markus.
> Invert loop

- openshift/e2e-tests-openshift.sh
Changes that are necessary after merging openshift/release#2209
> Use knative-eventing- prefix for images

- openshift/e2e-tests-openshift.sh
- openshift/kubecon-demo.sh
Fixes load balancer resource leaks in GCP.
> Clean resources after tests

- openshift/e2e-tests-openshift.sh
- openshift/kubecon-demo.sh
Sending these two together because both are required for the tests to pass.
> Image naming and fix for Demo

- openshift/e2e-tests-openshift.sh
* re-order tagging images and setting image-puller permissions, this is
required for --insecure=true tagging
This is for the master branch.
> Pass parameters easily for local testing

- openshift/e2e-tests-openshift.sh
- openshift/kubecon-demo.sh
- test/crd.go
- vendor/github.com/knative/test-infra/scripts/library.sh
Depends on https://github.com/openshift/knative-eventing/pull/25 which needs to be integrated first. Then we can let CI verify the current PR.
> Test script for release-0.3 OpenShift 4

- openshift/e2e-tests-openshift.sh
Instead of installing upstream Istio, lets run CI using the Maistra operator.
> Use the Maistra operator for Istio

- Makefile
- OWNERS_ALIASES
- openshift/e2e-tests-openshift.sh
- openshift/release/README.md
- openshift/release/create-release-branch.sh
- openshift/release/update-to-head.sh
> Houskeeping ocp files and add matzew owner

- ci
> Ci trigger

- ci
> CI was here

- openshift/olm/knative-eventing.catalogsource.yaml
- openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
as per title
@jcrossley3 @vdemeester
> Replaces fix like serving PR #60

- Makefile
- openshift/e2e-tests-openshift.sh
- openshift/release/create-release-branch.sh
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-v0.4.1.yaml
- openshift/release/resolve.sh
Fixes #https://jira.coreos.com/browse/SRVKE-43
> Release yaml v0.4.1

- Makefile
- openshift/e2e-tests-openshift.sh
- openshift/release/create-release-branch.sh
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-v0.5.0.yaml
- openshift/release/resolve.sh
Same as https://github.com/openshift/knative-eventing/pull/45 , just for release-v0.5.0 branch.
> Release yaml v0.5.0

- openshift/olm/knative-eventing.catalogsource.yaml
- openshift/olm/knative-eventing.v0.4.1.clusterserviceversion.yaml
> fixes for the OLM

- README.md
@vdemeester  like you did for build
> Adding initial readme

- openshift/olm/knative-eventing.catalogsource.yaml
@maschmid  patching the file here, as discussed on SRVKE-70
> Adding finalizers

- .gitignore
- openshift/release/knative-eventing-v0.5.0.yaml
- openshift/release/resolve.sh
checking in newly generated YAML
> Improving resolver

- openshift/release/knative-eventing-v0.5.0.yaml
> Adding webhook fix to generated file

- openshift/olm/knative-eventing.catalogsource.yaml
> Hot fix for SRVKE-70

- config/200-broker-clusterrole.yaml
- openshift/release/knative-eventing-v0.5.0.yaml
fixing the issue w/ the lacking filter CluterRole
> SRVKE-77 fix 

- openshift/olm/knative-eventing.catalogsource.yaml
as per title. ...
* moving args up
* adding `description` and `displayName`
> OLM updates

- cmd/webhook/main.go
- config/400-webhook-service.yaml
> Non priviliged 

- openshift/ci-operator/generate-ci-config.sh
- openshift/e2e-tests-openshift.sh
feedback from @mgencur on CI job enablement
> CI generator and registry changes inside

- config/200-controller-clusterrole.yaml
- config/provisioners/in-memory-channel/in-memory-channel.yaml
- openshift/release/knative-eventing-v0.5.0.yaml
/cc @jcrossley3  one more thing
> Some more rbac fun

- openshift/release/knative-eventing-v0.6.0.yaml
This is the file for the knative-eventing-operator
> Add knative-eventing-v0.6.0.yaml

- openshift/release/update-to-head.sh
> Latest version from serving, borrowed

- openshift/e2e-tests-openshift.sh
Same as https://github.com/openshift/knative-eventing/pull/91 but for master branch. Let's wait for the other PR to pass tests before integrating this.
> Fix machineset selector

- OWNERS_ALIASES
adding the team mates from the knative-eventing team
> Adding new approvers

- openshift/e2e-tests-openshift.sh
updates include:
* fixing for makefile, to compile/install the right image (sources_controller)
* updates to the actual docker image (for the renamed image)
* updates to `resolve.sh` and re-genrated the `ci` release yaml
> New image rename and better release resolve

- openshift/e2e-tests-openshift.sh
> latest, greatest filez

- openshift/e2e-tests-openshift.sh
porting #105 to `release-next`
> patching maistra for 0.6.0

- openshift/olm/knative-eventing.catalogsource.yaml
stashing latest OLM on master ... for nightly checkouts ...
> Adding OLM for 0.6.0

- openshift/e2e-tests-openshift.sh
porting #124 to master branch, so that we can `stash` it here for our nightly newly created `release-next` branch 
@lberk @syedriko @alanconway
> Going to use serving 0.6.0 operator, that installs Maistra

- openshift/olm/knative-eventing.catalogsource.yaml
updating file, generated using `./hack/catalog.sh` from the eventing operator .....
> using latest OLM generated file

- openshift/e2e-tests-openshift.sh
Porting #127 to master (tests passed ;-) )
Please check, @lberk or @syedriko
> remove sources

- openshift/e2e-tests-openshift.sh
@lberk  using 0.6.0 operator, that allso installs istio/maistra  (like on master/release-next)
> using latest Serving Operator (0.6.0) for our product

- openshift/e2e-tests-openshift.sh
- openshift/release/knative-eventing-ci.yaml
Similar to the 0.6.0 release branch on our SERVING fork, we are using our own (eventing) Operator, to test our eventing 0.6.0 release
> Using eventing operator

- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-kafka-v0.6.0.yaml
> Vendoring of our own images, like w/ eventing-core

- Makefile
- openshift/ci-operator/knative-images/kafka-channel-crd-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka-channel-crd-dispatcher/Dockerfile
- openshift/ci-operator/knative-images/kafka-channel-crd-webhook/Dockerfile
- openshift/release/generate-kafka.sh
- openshift/release/generate-release.sh
- openshift/release/resolve.sh
master version/port of #155  @lberk
> Tweak release script master

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
> Using eventing operator to install eventing

- Makefile
- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/knative-test-images/latency/Dockerfile
- openshift/ci-operator/knative-test-images/sequencestepper/Dockerfile
@lberk repairing the image related test failure
> Update master for recent

- openshift/olm/knative-eventing.catalogsource.yaml
using the override to actually use our own built images
> Use our own images on the 070 branch

- openshift/e2e-tests-openshift.sh
see #186 for the actual test, @lberk
> Install Strimzi, and remove Knative build

- openshift/e2e-tests-openshift.sh
> run e2e test in 35m and create SA

- openshift/e2e-tests-openshift.sh
port of #241 to master 
@lberk
> Move olm namespace to openshift-marketplace after OpenShift 4.2

- config/200-clusterrole-namespaced.yaml
- openshift/release/knative-eventing-v0.7.1.yaml
Fix for SRVKE-134, basically backport original change (and latest upstream version) from @lberk to this release branch
/assign @lberk 
/assign @mgencur
> Srvke 134 oc all backport

- openshift/release/knative-eventing-v0.8.0.yaml
Fixes [SRVKE-160](https://jira.coreos.com/browse/SRVKE-160)
/assign @maschmid
> Backporting patch from 071 t0 08x line

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
* enabling OML override and using operator w/ `ci` images
* removing code that was commented out beore
> re-enabling OLM files for upstream override + clean ups

- openshift/release/knative-eventing-ci.yaml
Synchroinzes the CI configuration with the change already merged in https://github.com/openshift/knative-eventing/pull/287/files
> Sync knative-eventing-ci.yaml, re SRVKE-160

- openshift/ci-operator/build-image/Dockerfile
Like https://github.com/openshift/knative-serving/pull/272
POST 0.9.0 we need 1.13
> Build binaries w/ 1.13

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
- openshift/patches/001-no-random-namespace-names.patch
- openshift/patches/002-imc-ocp-rbac.patch
- openshift/release/generate-release.sh
- openshift/release/update-to-head.sh
- openshift/serverless/operator-install.yaml
actual check-in of #293 content, with patches (rbac and testfile update)
> Prepare of release next work, with two patches to ensure tests run

- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-v0.9.0.yaml
Fixing SRVKE-130 on 0.9.0 branch
> Apply NetworkPolicy patch (see SRVKE-130)

- Gopkg.lock
- Gopkg.toml
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
patching used yaml.2 lib, to be on latest...
> Yaml fix 090

- openshift/e2e-tests-openshift.sh
> We still do test on 4.1, hence the OLM fu is back :fire:

- openshift/e2e-tests-openshift.sh
- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-v0.9.0.yaml
- test/e2e/broker_channel_flow_test.go
Fix for https://jira.coreos.com/browse/SRVKE-183 - on 0.9.0 release branch
> Adding finalizer RBAC for generic channel

- Makefile
- README.md
- openshift/ci-operator/generate-dockerfiles.sh
- openshift/ci-operator/update-ci.sh
- openshift/release/README.md
- openshift/release/create-release-branch.sh
- openshift/release/resolve.sh
Signed-off-by: Alan Conway <aconway@redhat.com>
> Release automation and documentation.

- OWNERS_ALIASES
> Add aliok as approver and reviewer

- openshift/olm/knative-serving.catalogsource.yaml
latest images for openshift/knative-serving 0.9.x
> updates of the OLM for serving

- openshift/olm/knative-eventing.catalogsource.yaml
and we now host some NetworkPolicy rules
> We no longer touch the SMMR, no RBAC needed 

- openshift/olm/knative-serving.catalogsource.yaml
generated the latest "serving" OLM, using the master of serverless-operator...
> updating to latest Serverless Operator

- openshift/e2e-tests-openshift.sh
> Iincreasing timeout

- openshift/olm/knative-eventing.catalogsource.yaml
Image is based on https://github.com/matzew/knative-eventing-operator/tree/prep_for_0.13
...
> Adding latest from 0.13_prep

- openshift/e2e-tests-openshift.sh
porting https://github.com/openshift/knative-eventing/pull/454  to master
> Updates to ci run

- pkg/apis/eventing/v1alpha1/trigger_conversion.go
- test/e2e/trigger_dependency_annotation_test.go
- test/lib/resources/eventing.go
Porting upstream 2700 here ...
> Port trigger fix ocp

- OWNERS_ALIASES
Please ping me directly if my review is needed for a PR
> Remove myself from approvers/reviewers

- openshift/e2e-tests-openshift.sh
run against RELEASE_NEXT was successful: see #473
> adding smoother install for serverless

- openshift/e2e-tests-openshift.sh
like on master.
until we have the 1.6.0 release, we are going to use MASTER/HEAD from the serverless-operator
> adding smoother install for serverless 

- Gopkg.lock
- vendor/knative.dev/pkg/injection/sharedmain/main.go
- vendor/knative.dev/pkg/metrics/exporter.go
Applying patch from Paul for updating the pkg to 0.13.0 .
see upstream: https://github.com/knative/eventing/commit/d14bc9614dcacfa91d0e1fd62cfbde6eaeef68f9
> Update to latest pkg 0.13 (#2727)

- openshift/ci-operator/update-ci.sh
> Remove 4.2 and use only 43/44/45 runs for _release_ branches

- Makefile
- openshift/ci-operator/generate-dockerfiles.sh
chanign broker image BUILD path, for CI
> Brokers are now there twice, so we two filters, and two ingress

- config/brokers/channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/500-controller.yaml
- config/channels/in-memory-channel/500-dispatcher.yaml
- config/core/deployments/sources-controller.yaml
- openshift/release/knative-eventing-v0.13.0.yaml
Cherry pick and modify https://github.com/knative/eventing/issues/2794
@matzew I just created the PR against 0.13.0 branch. Should we create a new branch? Don't know if our CI is able to mutate the artifacts after they're released - ideally it shouldn't.
> Consistent and unique container names

- openshift/release/generate-release.sh
For the MTbroker, we now will have a separate release yaml
> Create separate mtbroker release artifact

- openshift/release/generate-release.sh
> generate channel broker yamls

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
> Updating test run and latest operator bits, shipping Channel Broker

- openshift/e2e-tests-openshift.sh
- openshift/olm/knative-eventing.catalogsource.yaml
- openshift/patches/010-trigger_dependency-skip_tests.patch
> Updates to e2e

- openshift/olm/knative-eventing.catalogsource.yaml
> Adding the mt broker yamls

- openshift/e2e-tests-openshift.sh
> Test clean up

- openshift/release/resolve.sh
> Fixing the actual resolved images to the real ones

- openshift/release/update-to-head.sh
> comment out the patching

- openshift/ci-operator/generate-ci-config.sh
> Adding a few more hacks for 'propper' image names on OCP... :fire:

- openshift/e2e-tests-openshift.sh
> Stash the file on the right place

- openshift/e2e-tests-openshift.sh
> Reflecting new configs and stuff

- openshift/e2e-tests-openshift.sh
> Use image template

- Makefile
> We do not have the Filter/Ingress for the ST broker anymore

- openshift/ci-operator/build-image/Dockerfile
> Use Golang 1.14 on container builds

- openshift/ci-operator/source-image/Dockerfile
Same as #608, just for master branch
Will be used in openshift/release#9455
> Dockerfile for source image

- openshift/e2e-tests-openshift.sh
> Run only MT broker

- OWNERS_ALIASES
Adds the new eventing team member abd4lla to the owners list and reorder owners alphabetically.
> Add Ahmed Abdalla to the OWNERS_ALIASES and reorderd the list

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> Trying to use the 1.8.0 operator

- openshift/release/knative-eventing-channelbroker-ci.yaml
> fix image names

- test/e2e/parallel_test.go
- test/e2e/sequence_test.go
> Disable TestFlowsParallel and TestFlowsSequence

- openshift/e2e-common.sh
- openshift/release/generate-release.sh
- openshift/release/resolve.sh
Also adjust the way specific tests are run via bash var
> Update CI yaml to include sugar-controller

- openshift/e2e-common.sh
> Test the images built in this PR (not via operator)

- Makefile
- openshift/ci-operator/knative-images/migrate/Dockerfile
> Add storage version migration image.

- Makefile
- openshift/ci-operator/knative-images/migrate/Dockerfile
Same as https://github.com/openshift/knative-eventing/pull/722
> [RELEASE-v0.16.0] Add storage version migration image.

- openshift/e2e-common.sh
> Fixing test invoke

- openshift/e2e-common.sh
> Apply invokefix master

- openshift/ci-operator/build-image/Dockerfile
> Adding httpd-tools

- openshift/e2e-common.sh
- openshift/olm/serverless-operator.clusterserviceversion.yaml
- test/e2e/source_sinkbinding_v1alpha1_test.go
- test/e2e/source_sinkbinding_v1alpha2_test.go
Trying to fix errors from https://github.com/openshift/knative-eventing/pull/752
> Move forward w/ new bundle, and skip binding tests

- openshift/patches/014-sinkbinding_tests_skip.patch
> fixing double patches

- openshift/e2e-common.sh
> We no longer have the old channel broker

- openshift/patches/013-sinkbinding_webhook_corrections.patch
> Correct the patch, since we no longer need to set to Ignore

- openshift/release/create-release-branch.sh
> Adding the patch apply fu to the script for new release branches

- pkg/reconciler/mtbroker/trigger/controller.go
- pkg/reconciler/mtbroker/trigger/trigger.go
backporting 3966 from upstream
> [backport] 0.17.2: Enqueue Triggers on Broker changes

- openshift/release/knative-eventing-ci.yaml
as per title (done via `make RELEASE=v0.17.2 generate-release `)
> Regenerating the release yaml

- test/conformance/helpers/broker_data_plane_test_helper.go
> Some little test fix / backport

- test/e2e/source_sinkbinding_v1alpha1_test.go
- test/e2e/source_sinkbinding_v1alpha2_test.go
> Skipping tests, like on all other brnaches

- openshift/e2e-common.sh
- openshift/serverless.bash
> Using latest product for 017 branch

- openshift/patches/012-skip-tracing-conformance.patch
> correcting the patch

- pkg/reconciler/subscription/subscription.go
- pkg/reconciler/subscription/subscription_test.go
packporting upstream 4042 to here
> Cherry pick 4042 and port to this branch

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
Backport of #673    from @mgencur
> Modify scripts to be reusable in serverless-operator repo (#673)

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> We run Strimzi/Kafka in contrib

- openshift/e2e-common.sh
> using oc replace in pipe

- openshift/ci-operator/build-image/Dockerfile
> Install yq in the build image for CI

- test/lib/duck/resource_checks.go
> Port 4093 to our 0.17

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
- test/e2e/helpers/broker_redelivery_helper.go
Backporting #4114 by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
> Set check retry function (#4114)

- openshift/ci-operator/build-image/Dockerfile
like https://github.com/openshift-knative/serverless-operator/pull/481
> [0.16] Using fqn image name

- openshift/ci-operator/build-image/Dockerfile
like https://github.com/openshift-knative/serverless-operator/pull/481
> [master] Using fqn image name

- openshift/ci-operator/build-image/Dockerfile
like https://github.com/openshift-knative/serverless-operator/pull/481
> [0.17] Using fqn image name

- config/core/deployments/webhook.yaml
> backport upstream 4168 to out .17

- config/core/deployments/webhook.yaml
> backport upstream 4168 to out .16

- openshift/e2e-common.sh
> Using OC instead of k alias

- openshift/release/knative-eventing-ci.yaml
> Regenerating the release yaml, based on patches

- Makefile
> [master] Going back to for loop for image builds

- Makefile
> [0.16] Going back to for loop for image builds

- Makefile
> [0.18] Going back to for loop for image builds

- Makefile
> [0.17] Going back to for loop for image builds

- openshift/e2e-common.sh
> Reduce the parallel to avoid timeouts

- pkg/reconciler/inmemorychannel/dispatcher/controller.go
> backport of 4280

- openshift/e2e-common.sh
- openshift/serverless.bash
> [0.17] Updating the product base to 1.10 release

- openshift/e2e-common.sh
> [0.18] align with release-17

- openshift/e2e-common.sh
> Go w/ 4 parallel

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> [0.17] Separate e2e and conformance tests, like done on upstream

- openshift/e2e-common.sh
Just cosmetics:
* moving `install_tracing` functions up
* change the header to reflect with (E2E / conformance) test we run
/assign @lberk
> Move around the functions for installing/configuration tracing

- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
> Using hack repo

- pkg/kncloudevents/message_sender.go
- pkg/kncloudevents/message_sender_test.go
>  [0.17] Fix #4425

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> [0.17] Enable tracing

- test/e2e/trigger_dependency_annotation_test.go
> use beta1 pingsrc

- openshift/e2e-common.sh
> Release-next: tweaks 

- openshift/e2e-common.sh
> [0.17] Bump parallel

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
Doing 
* #932
* #929 
on the 0.18.3 branch
> Enable tracing and e2e bump 0.18

- openshift/e2e-common.sh
Like in #936 - but on master, so we have it on `release-next`, for real.....
> Reduce the timeouts a bit

- openshift/ci-operator/update-ci.sh
> We only have one job, for 4.6 OCP

- cmd/mtbroker/ingress/main.go
- pkg/kncloudevents/http_client.go
- pkg/kncloudevents/http_client_test.go
- pkg/kncloudevents/message_sender.go
- pkg/mtbroker/filter/filter_handler.go
- pkg/reconciler/inmemorychannel/dispatcher/controller.go
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> [0.17] Backport #4465 (#4467)

- pkg/mtbroker/filter/filter_handler.go
- pkg/mtbroker/filter/filter_handler_test.go
> [0.17] Port 4466 

- pkg/reconciler/apiserversource/resources/receive_adapter.go
- pkg/reconciler/apiserversource/resources/receive_adapter_test.go
backporting an upstream backport see: 4479
> [0.17] backporting 4479

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- openshift/release/knative-eventing-mtbroker-ci.yaml
- pkg/mtbroker/ingress/ingress_handler.go
This needs to also go to the operator,... has that ships the real, fancy yamls
> [0.17] SRVKE-629

- openshift/e2e-common.sh
in https://github.com/openshift-knative/serverless-operator/blob/release-1.10/hack/lib/catalogsource.bash#L27-L29
> attempt to not fall into the "CI" branch trap

- openshift/ci-operator/generate-ci-config.sh
Changes to the script, which I used to generate this PR:
https://github.com/openshift/release/pull/13538
> Update script to reflect new CI cfg 

- openshift/e2e-common.sh
> unset OPENSHIFT_CI

- pkg/reconciler/source/crd/crd.go
Note: crd_test.go isn't fixed in this release (thus no testcase added)
related: [SRVKE-632](https://issues.redhat.com/browse/SRVKE-632)
> source.crd controller: filter out non duck crds

- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-mtbroker-ci.yaml
> [0.18.4] Running yaml generator

- config/core/resources/channel.yaml
- config/pre-install/v0.18.0/channel.yaml
- openshift/release/knative-eventing-ci.yaml
> Adding some more backprts

- openshift/ci-operator/generate-ci-config.sh
port of #971 to HEAD
(see link for details)
> [HEAD] Adding new ci cfg format to generator (#971)

- Makefile
- openshift/ci-operator/knative-images/chaosduck/Dockerfile
For future generator builds
See also: https://github.com/openshift/release/pull/13827
> [master] Adding Chaosduck image

- pkg/reconciler/inmemorychannel/controller/resources/service.go
- pkg/reconciler/mtbroker/resources/channel.go
> Make channels and services of the correct length (#4558)

- openshift/ci-operator/update-ci.sh
same as https://github.com/openshift/knative-eventing/pull/1005, but for master
> [head] Adding back the image mirror, but only for test images.

- openshift/ci-operator/update-ci.sh
> [0.18] Adding OCP 4.7 run to CI job

- openshift/ci-operator/update-ci.sh
> using the proper name for the mirrored images to quay.io

- openshift/ci-operator/update-ci.sh
> making the generator script easier to read

- config/core/deployments/pingsource-mt-adapter.yaml
- openshift/release/knative-eventing-ci.yaml
> [0.18] Setting replica in yaml to 1, and regenerate the file

- config/channels/in-memory-channel/deployments/dispatcher.yaml
- openshift/release/knative-eventing-ci.yaml
> [0.18.6] Porting 4640 to OCP

- openshift/e2e-common.sh
> Using latest of product

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
cleaner install and after test run, we tear it down...
> Adding teardown of eventing

- RELEASE.md
> Help to improve the release doc

- README.md
- RELEASE.md
A couple small updates found for the v0.20 release bits
> Update release.md, readme.md

- openshift/ci-operator/update-ci.sh
- openshift/release/README.md
Instead of doing this manually, script it!
> Automate adding reporter_config to update-ci script, add to readme

- openshift/release/mirror-upstream-branches.sh
hopefully this fixes the jenkins error we're seeing
> Modify mirror-upstream-branches.sh to use --all instead of --remotes

- README.md
- openshift/release/README.md
- openshift/release/create-release-branch.sh
- openshift/release/update-to-head.sh
> Make the scripts use main instead of master

- openshift/ci-operator/build-image/Dockerfile
- openshift/e2e-common.sh
> Fixing one more old registy usage

- openshift/e2e-common.sh
> [MAIN] Use the latest version of product offering

- openshift/e2e-common.sh
> :lipstick: Use the latest version of product offering

- pkg/apis/eventing/v1beta1/broker_validation.go
Co-authored-by: Yi Zhang <cathyzhyi@google.com>
/hold
> [0.20 backport] Add immutable fields validation to v1beta1 broker (#5028)

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
> [0.21] a few more usages of svc.ci registry

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
> [0.20] a few more usages of svc.ci registry

- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
> [main] a few more usages of svc.ci registry

- openshift/ci-operator/build-image/Dockerfile
- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-mtbroker-ci.yaml
> [0.18.6] a few more usages of svc.ci registry

- go.mod
- go.sum
- vendor/knative.dev/pkg/metrics/resource_view.go
- vendor/modules.txt
Fetching https://github.com/knative/eventing/pull/5122
> Add fix for oom

- openshift/ci-operator/build-image/Dockerfile
- openshift/e2e-common.sh
- openshift/e2e-tests-local.sh
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-mtbroker-ci.yaml
> [0.19.2] a few more usages of svc.ci registry

- pkg/apis/messaging/v1/subscription_defaults.go
- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
- pkg/apis/messaging/v1beta1/subscription_defaults.go
- pkg/apis/messaging/v1beta1/subscription_validation.go
- pkg/apis/messaging/v1beta1/subscription_validation_test.go
Signed-off-by: Francesco Guardiani <francescoguard@gmail.com>
> [0.21] KafkaChannel hack to upgrade (#5085)

- openshift/e2e-common.sh
Taking #1211 to reality 
/assign @lberk
> [MAIN] Update source versions on e2e/conformance tests

- openshift/e2e-common.sh
like https://github.com/openshift/knative-eventing/pull/1219
but for 0.21
> [0.21] Align the source version schema for our 0.21 branch

- openshift/e2e-common.sh
like https://github.com/openshift/knative-eventing/pull/1219
but for 0.22
> [0.22] Align the source version schema for our 0.22 branch

- test/lib/creation.go
backport https://github.com/knative/eventing/pull/5313
> [0.22.0] backport CreatePodOrFail retry on "No API token found" (#5313)

- test/lib/creation.go
> [0.21.0] backport CreatePodOrFail retry on "No API token found" (#5313)

- test/lib/creation.go
> [0.20.0] backport CreatePodOrFail retry on "No API token found" (#5313)

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> See if we can run the rek tests here too

- pkg/reconciler/channel/channel.go
- pkg/reconciler/channel/channel_test.go
- pkg/reconciler/mtbroker/broker.go
> Adding downstream checks for KafkaChannel v1a1

- pkg/reconciler/broker/broker.go
- pkg/reconciler/channel/channel.go
- pkg/reconciler/channel/channel_test.go
- test/e2e/channel_chain_test.go
> [0.22] Tweak channel template

- vendor/knative.dev/pkg/resolver/addressable_resolver.go
Seems like this fixes [SRVKE-780](https://issues.redhat.com/browse/SRVKE-780)
> [Backport] Allow URIs to be resolved without reconciler context (#2095)

- openshift/e2e-common.sh
> [0.21] Using the Serverless 1.15 product

- openshift/e2e-common.sh
> [0.22] Using the Serverless 1.15 product

- vendor/knative.dev/pkg/webhook/certificates/certificates.go
- vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
- vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
> [0.23] Rollback certificate algorithm changes (#1281)

- vendor/knative.dev/pkg/controller/stats_reporter.go
- vendor/knative.dev/pkg/metrics/resource_view.go
- vendor/knative.dev/pkg/resolver/addressable_resolver.go
- vendor/knative.dev/pkg/webhook/certificates/certificates.go
- vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
- vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
- vendor/knative.dev/pkg/webhook/stats_reporter.go
Because if #1286 the important changes for #1281, #1274, #1266 and #1223 got undone ...
Re applying them here again
> [0.21] backport 1281, 1274, 1266 and 1223

- openshift/ci-operator/build-image/Dockerfile
Bump to Golang 1.16 based on https://github.com/knative/eventing/blob/main/go.mod#L3
> Bump to Golang 1.16

- pkg/reconciler/broker/broker.go
- pkg/reconciler/channel/channel.go
- pkg/reconciler/channel/channel_test.go
* Adding downstream checks for KafkaChannel v1a1
* Adding the hack to the broker too
> [0.23] SRVKE-796 patch

- openshift/release/mirror-upstream-branches.sh
> Change the name of the mistream release branch to be just X.Y

- pkg/channel/message_dispatcher.go
As upstream here: https://github.com/knative/eventing/pull/5512 and patch as in here: https://github.com/openshift-knative/eventing-kafka/pull/234
> Pass transformers to executeRequest

- openshift/ci-operator/update-ci.sh
@matzew hopefully this will solve the mirroring script for 0.23+ as you mentioned
> Add version suffix to registry mirroring generator script

- openshift/e2e-common.sh
> Using 1.16 version of product

- openshift/patches/018-rekt-test-image-changes.patch
- openshift/release/update-to-head.sh
Fix rekt patch to get nightly job running.
> Fix rekt patch to get nightly job running

- Makefile
> To get the build back we disable the REKT TESTs, for now

- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/apiserver_receive_adapter/Dockerfile
- openshift/ci-operator/knative-images/channel_controller/Dockerfile
- openshift/ci-operator/knative-images/channel_dispatcher/Dockerfile
- openshift/ci-operator/knative-images/chaosduck/Dockerfile
- openshift/ci-operator/knative-images/controller/Dockerfile
- openshift/ci-operator/knative-images/filter/Dockerfile
- openshift/ci-operator/knative-images/ingress/Dockerfile
- openshift/ci-operator/knative-images/migrate/Dockerfile
- openshift/ci-operator/knative-images/ping/Dockerfile
- openshift/ci-operator/knative-images/pong/Dockerfile
- openshift/ci-operator/knative-images/sendevent/Dockerfile
- openshift/ci-operator/knative-images/webhook/Dockerfile
- openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-test-images/logevents/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/sendevents/Dockerfile
Add same non-root user as Serving's images have.
https://github.com/openshift/knative-serving/commit/c516f6b12f9dc9840c2c39c9fbd5eca2eb6c163f
> Add non-root user to CI built images

- openshift/e2e-common.sh
> [0.25] Use 1.17 product branch

- openshift/e2e-common.sh
> [main] Use 1.17 product branch

- openshift/e2e-common.sh
> [0.23] Use 1.17 product branch

- openshift/e2e-common.sh
> [0.24] Use 1.17 product branch

- openshift/ci-operator/generate-ci-config.sh
Generates CI config using cluster pools that is used in https://github.com/openshift/release/pull/21286
> [release-v0.24] Generate cluster pool stanza for OCP 4.8

- config/core/resources/trigger.yaml
- pkg/apis/sources/v1/ping_validation.go
- pkg/apis/sources/v1/ping_validation_test.go
- pkg/apis/sources/v1beta2/ping_validation.go
- pkg/apis/sources/v1beta2/ping_validation_test.go
- test/experimental/delivery_timeout_test.go
- test/rekt/features/broker/readyness.go
- test/rekt/resources/broker/broker.go
- test/rekt/resources/broker/broker.yaml
- test/rekt/resources/delivery/delivery.go
- test/rekt/resources/trigger/trigger.go
- test/rekt/resources/trigger/trigger.yaml
Adding some backports from upstream
* https://github.com/knative/eventing/commit/b4cabbf050a814617c516dbdb50ae51a4d5bf6fa
* https://github.com/knative/eventing/commit/36c4252bcd16b6f0e2896a9302f547bc5801f5a2
/assign @lberk 
> [0.24] backports from upstream

- README.md
> Some proposal for release scheduling

- openshift/e2e-common.sh
Fixing https://issues.redhat.com/browse/SRVKE-918
> [release-v0.24] Wait for test NS to be deleted after REKT tests

- openshift/patches/019-remove-tracing-observability-yamls.patch
> Fixing patch, to now also recognize the k8s labels

- openshift/ci-operator/generate-ci-config.sh
- openshift/e2e-common.sh
- openshift/e2e-conformance-tests.sh
- openshift/e2e-rekt-tests.sh
- openshift/e2e-tests-local.sh
- openshift/e2e-tests.sh
Includes changes from several PRs that were already merged in release-v0.24
> [release-v0.25] Prepare for cluster pools

- openshift/e2e-common.sh
> [main] Using 1.18 product brnach

- openshift/e2e-common.sh
> [release-v0.24] Using 1.18 product brnach

- openshift/e2e-common.sh
> [release-v0.25] Using 1.18 product branch

- README.md
Putting me on to later releases!
> Adjusting the table for release work

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
> [release-v0.25] Adding 4.9 for ci generator

- OWNERS_ALIASES
As per title.
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
> Add pierDipi to OWNERS_ALIASES

- pkg/apis/messaging/v1/channel_validation.go
- pkg/apis/messaging/v1/channel_validation_test.go
- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
Co-authored-by: I867318 <travis.minke@sap.com>
> [release-v0.24] Backport: Validate DeliverySpec in Channels & Subscriptions (#5780)

- pkg/apis/messaging/v1/channel_validation.go
- pkg/apis/messaging/v1/channel_validation_test.go
- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
Co-authored-by: I867318 <travis.minke@sap.com>
> [release-v0.26] Backport: Validate DeliverySpec in Channels & Subscriptions (#5778)

- pkg/apis/messaging/v1/channel_validation.go
- pkg/apis/messaging/v1/channel_validation_test.go
- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
Co-authored-by: I867318 <travis.minke@sap.com>
> [release-v0.25] Backport: Validate DeliverySpec in Channels & Subscriptions (#5779)

- openshift/release/mirror-upstream-branches.sh
> Knative has knative in release version name

- openshift/ci-operator/build-image/Dockerfile
related to https://github.com/openshift-knative/serverless-operator/pull/1302
Let's see how this really goes...
> [release-v0.26] Golang 1.17 container image

- openshift/ci-operator/build-image/Dockerfile
backport of https://github.com/openshift/knative-eventing/pull/1475
> [main] Golang 1.17 container image

- openshift/ci-operator/build-image/Dockerfile
backport of https://github.com/openshift/knative-eventing/pull/1475
> [release-v1.0] Golang 1.17 container image

- README.md
> Reflecting new upstream release version numbers

- openshift/ci-operator/build-image/Dockerfile
porting of https://github.com/openshift/knative-eventing/pull/1483
> Remove ansible

- openshift/ci-operator/build-image/Dockerfile
> [release-v0.26] Remove ansible

- openshift/e2e-common.sh
> [release-0.26] Checkout Serverless Operator 1.20 branch

- README.md
/assign @aliok @devguyio @matzew @lberk
> Update CI duty table

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
like https://github.com/openshift/knative-eventing/pull/1547/files  
But just for 1.1 ...
> [release-1.1] Actual version for rekt test

- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
> [v0.26] Make SubscriptionSpec.Delivery mutable

- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
> [v1.0] Make SubscriptionSpec.Delivery mutable

- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
> [v1.1] Make SubscriptionSpec.Delivery mutable

- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
> [v1.2] Make SubscriptionSpec.Delivery mutable

- pkg/apis/messaging/v1/subscription_validation.go
- pkg/apis/messaging/v1/subscription_validation_test.go
> [v0.25] Make SubscriptionSpec.Delivery mutable

- config/core/resources/channel.yaml
- docs/eventing-api.md
- pkg/apis/messaging/v1/channel_template_types.go
- test/rekt/channel_test.go
- test/rekt/features/channel/features.go
- test/rekt/resources/channel/channel.go
- test/rekt/resources/channel/channel_test.go
- test/rekt/resources/channel_impl/channel_impl.go
Cherry-pick of https://github.com/knative/eventing/pull/6261/files
> [release-1.3] Set dead letter sink URI in the `Channel` status (#6261)

- openshift/ci-operator/build-image/kubernetes.repo
Similar to https://github.com/openshift/knative-eventing/pull/1185
> [SRVKE-1181] Skip GPG check for kubernetes repository

- config/core/resources/sequence.yaml
- openshift/release/knative-eventing-ci.yaml
- pkg/reconciler/parallel/parallel.go
- pkg/reconciler/sequence/sequence.go
- pkg/reconciler/sequence/sequence_test.go
- test/rekt/features/parallel/readyness.go
- test/rekt/features/sequence/readyness.go
- test/rekt/resources/delivery/delivery.go
- test/rekt/resources/parallel/parallel.go
- test/rekt/resources/parallel/parallel.yaml
- test/rekt/resources/parallel/parallel_test.go
- test/rekt/resources/sequence/sequence.go
- test/rekt/resources/sequence/sequence.yaml
- test/rekt/resources/sequence/sequence_test.go
- test/rekt/smoke_test.go
porting https://github.com/knative/eventing/commit/282bba706eaa13583788eca5f28288655ed945e0
and regenerating the manifest
> [release-v1.0] Fix channel template spec type for sequence channel template field

- pkg/reconciler/broker/trigger/controller.go
- pkg/reconciler/broker/trigger/controller_test.go
- pkg/reconciler/broker/trigger/trigger.go
See the matching 1.0 upstream commit:
https://github.com/knative/eventing/commit/ae90c1f58eae8962a18bbe7988e215bb89feea98
> [release-1.0] Backport of upstream 6265

- config/core/resources/channel.yaml
- docs/eventing-api.md
- pkg/apis/messaging/v1/channel_template_types.go
- test/rekt/channel_test.go
- test/rekt/features/channel/features.go
- test/rekt/resources/channel/channel.go
- test/rekt/resources/channel/channel_test.go
- test/rekt/resources/channel_impl/channel_impl.go
Cherry-pick https://github.com/knative/eventing/pull/6262/files
> [release-1.2] Set dead letter sink URI in the `Channel` status (#6262)

- openshift/ci-operator/generate-ci-config.sh
> Prepare for future version when generating the periodics

- openshift/release/knative-eventing-ci.yaml
- openshift/release/knative-eventing-mtbroker-ci.yaml
can be merged _AFTER_ https://github.com/openshift/release/pull/27660 is in
> [release-v1.2] Update images to new version

- openshift/patches/005-k8s-min.patch
> Upate the min version

- test/upgrade/prober/verify.go
Backport this commit separately. For 1.2 and 1.3 it's already there.
> [release-v1.4] NPE fix (#6343)

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
Cleaning up the CI scripts, and adding 4.10 generator bits to the mix
> [release-v1.3] Adding 4.10 and do nightly periodics there, as well as image promotion

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
as per title
Reference: https://github.com/openshift/knative-eventing/pull/1704
> Porting 1704 to main

- openshift/ci-operator/update-ci.sh
> [release-v1.2] Adding 4.10 and do nightly periodics there, as well as image promotion

- pkg/broker/filter/filter_handler.go
Related: https://github.com/knative-sandbox/eventing-kafka-broker/issues/2122
Let's try this quickly downstream at SO and then I can create a PR in the upstream (and also other branches) asking for Security WG feedback.
This is very hard to test because when I tell the mock http server to send a specific `Content-Length` with the reply for checking, it responds with `502`
> Do not proxy some headers from reply

- RELEASE.md
> Updates on how simple the release cut now is for midstream eventing

- RELEASE.md
> Fix broken link

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> [release-v1.2] Use versioned images for rekt tests

- openshift/e2e-common.sh
> [release-v1.3] Switch back to use SO main branch

- config/channels/in-memory-channel/deployments/controller.yaml
- config/core/deployments/webhook.yaml
Cherry-pick of https://github.com/knative/eventing/commit/2d2e049138734aaca8c0b85c6a628c6a2c06f272
> [release-v1.3] Increase initialDelaySeconds to 120 for webhooks (#6447)

- Makefile
- openshift/ci-operator/knative-images/storage_version_migration/Dockerfile
Cherry-pick of https://github.com/openshift/knative-eventing/pull/1812
> [main] Move migrate image to storage_version_migration directory for consistency

- openshift/e2e-common.sh
> [release-v1.4] Use serverless operator main

- openshift/patches/018-rekt-test-override-kopublish.patch
> Ko publish changed, hence adjusting the patch

- pkg/broker/ingress/ingress_handler.go
- pkg/broker/ingress/ingress_handler_test.go
> [release-v1.5] Ignore trailing slashes for Broker addresses (#6471)

- openshift/patches/015-sinkbinding_v1_tests_skip.patch
> Adjust patch due to upstream change

- openshift/patches/015-sinkbinding_v1_tests_skip.patch
Fixing failure for changed test.
> Adjust more test due to changes

- openshift/ci-operator/generate-dockerfiles.sh
> [main] Generate build-image Go version

- pkg/channel/message_receiver.go
- pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
- test/rekt/features/channel/data_plane.go
backport from upstream to here...
> [release-1.5] InMemoryChannel receiver validates received events (#6514)

- pkg/channel/message_receiver.go
- pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
- test/rekt/features/channel/data_plane.go
backport from upstream to here...
> [release-1.6] InMemoryChannel receiver validates received events (#6513)

- pkg/channel/message_receiver.go
- pkg/channel/multichannelfanout/multi_channel_fanout_message_handler_test.go
- test/rekt/features/channel/data_plane.go
backport from upstream to here...
> [release-1.4] InMemoryChannel receiver validates received events (#6515)

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> [release-v1.3] Using proper versioned images for 1.3.2

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> [release-v1.4] Using proper versioned images for 1.4

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> [release-v1.5] Using proper versioned images for 1.5

- test/rekt/features/apiserversource/data_plane.go
- test/rekt/resources/containersource/containersource.yaml
- test/rekt/resources/containersource/containersource_test.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/eventlibrary/eventlibrary_test.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/flaker/flaker_test.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
> [release-v1.6] Using proper versioned images for 1.6

- test/lib/creation.go
like https://github.com/openshift/knative-eventing/pull/1889 but for 1.7 branch
> [release-v1.7] Do not use v1b1 from Cronjobs (#6537)

- test/e2e/source_sinkbinding_v1_test.go
- test/lib/creation.go
/hold
let's see what all env say to this
> [release-v1.5] Do not use v1b1 from Cronjobs

- openshift/patches/018-e2e-test-so-fix-TestBrokerNamespaceDefaulting.patch
- test/e2e/broker_defaults_webhook_test.go
> [release-v1.5] SRVKE-1265 SO specific patch for TestBrokerNamespaceDefaulting

- config/brokers/mt-channel-broker/deployments/broker-filter.yaml
- config/brokers/mt-channel-broker/deployments/broker-ingress.yaml
- config/brokers/mt-channel-broker/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/controller.yaml
- config/channels/in-memory-channel/deployments/dispatcher.yaml
- config/core/deployments/controller.yaml
- config/core/deployments/pingsource-mt-adapter.yaml
- config/core/deployments/webhook.yaml
- config/post-install/storage-version-migrator.yaml
- config/tools/appender/appender.yaml
- config/tools/event-display/event-display.yaml
- config/tools/heartbeats/heartbeats.yaml
- config/tools/recordevents/recordevents.yaml
- config/tools/websocket-source/websocket-source.yaml
- openshift/release/artifacts/eventing-core.yaml
- openshift/release/artifacts/eventing-post-install.yaml
- openshift/release/artifacts/in-memory-channel.yaml
- openshift/release/artifacts/mt-channel-broker.yaml
Like https://github.com/openshift/knative-eventing/pull/1898
but for 1.6......
> [release-v1.6] Fix scc drop all

- cmd/controller/main.go
- config/core/deployments/controller.yaml
- pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority.go
- pkg/scheduler/plugins/core/availabilitynodepriority/availability_node_priority_test.go
- pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority.go
- pkg/scheduler/plugins/core/availabilityzonepriority/availability_zone_priority_test.go
- pkg/scheduler/scheduler.go
- pkg/scheduler/statefulset/scheduler.go
- pkg/scheduler/statefulset/scheduler_test.go
- test/rekt/features/broker/control_plane.go
- test/rekt/features/broker/topology.go
Doing backports of the following upstream 1.6 branch PRs:
* https://github.com/knative/eventing/pull/6519
* https://github.com/knative/eventing/pull/6527
* https://github.com/knative/eventing/pull/6567
> [release-v1.6] Backports from upstream 

- test/lib/creation.go
- test/rekt/resources/eventlibrary/eventlibrary.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/flaker/flaker.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- vendor/knative.dev/pkg/test/security/security.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
- vendor/knative.dev/reconciler-test/pkg/manifest/options.go
> [release-v1.5] Set SecurityContext for test Pods

- test/lib/creation.go
- test/rekt/resources/eventlibrary/eventlibrary.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/flaker/flaker.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- vendor/knative.dev/pkg/test/security/security.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
- vendor/knative.dev/reconciler-test/pkg/manifest/options.go
> [release-v1.4] Set SecurityContext for test Pods

- test/lib/creation.go
- test/rekt/resources/eventlibrary/eventlibrary.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/flaker/flaker.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- vendor/knative.dev/pkg/test/security/security.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
- vendor/knative.dev/reconciler-test/pkg/manifest/options.go
> [release-v1.6] Set SecurityContext for test Pods

- test/lib/creation.go
- test/rekt/resources/eventlibrary/eventlibrary.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/flaker/flaker.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- vendor/knative.dev/pkg/test/security/security.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
- vendor/knative.dev/reconciler-test/pkg/manifest/options.go
> [release-v1.7] Set SecurityContext for test Pods

- test/lib/creation.go
- test/rekt/resources/eventlibrary/eventlibrary.go
- test/rekt/resources/eventlibrary/eventlibrary.yaml
- test/rekt/resources/flaker/flaker.go
- test/rekt/resources/flaker/flaker.yaml
- test/rekt/resources/pod/pod.go
- test/rekt/resources/pod/pod.yaml
- vendor/knative.dev/pkg/test/security/security.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go
- vendor/knative.dev/reconciler-test/pkg/k8s/pod.go
- vendor/knative.dev/reconciler-test/pkg/manifest/options.go
> [release-v1.8] Set SecurityContext for test Pods

- OWNERS_ALIASES
Adding myself (@creydr) to the OWNER_ALIASES
> Add creydr to OWNER_ALIASES

- README.md
Adding myself to the CI rotation table.
This effects only @lberk as this is only for this year. If this week, doesn't work for you (e.g. due to PTO), we could switch/replace.
> Add creydr to CI rotation table
